# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "ÚLTIMA VERSÃO"
  lane :ultima do
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "GitHubIssuesApp.xcodeproj"
    )
  end
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(workspace: "GitHubIssuesApp.xcworkspace", scheme: "GitHubIssuesApp")
    upload_to_testflight
  end
  before_all do
  end
  desc "Submit a new Beta Build to Apple TestFlight"
  lane :betaTESTE do
      # Add a badge to app icon. This will actually overwrite images, so be careful.
      # More info: https://github.com/HazAT/fastlane-plugin-badge & https://github.com/HazAT/badge
      add_badge(
          alpha: true,
          shield: "v#{ENV['XPI_VERSION']}.#{ENV['XPI_BUILD']}-blue"
          # shield: "Version-0.0.3-blue"
      )
      # build app
      gym(
          export_method: "app-store",
          export_options: {
              provisioningProfiles: {
                  "com.mobidevel.GitHubIssuesApp" => "match AppStore com.mobidevel.GitHubIssuesApp",
              }
          },
      scheme: "GitHubIssuesApp")
      # Upload build to testflight & set field "what's new"
      pilot(
          skip_waiting_for_build_processing: true,
          changelog: ENV['WHATS_NEW_MESSAGE']
      )
  end
  after_all do |lane|
      # This block is called, only if the executed lane was successful
  end
  error do |lane, exception|
  end
end
